load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "cpp-effects",
    visibility = ["//visibility:public"],
    hdrs = ["cpp-effects.hh", "clause-modifiers.hh"],
    deps = ["@boost//:context", "@fmt"],
)